# Generated by Django 2.2.6 on 2019-11-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('product_image', models.URLField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
            ],
        ),
    ]
