# Generated by Django 2.2.6 on 2019-11-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=30)),
                ('vender', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('product_image', models.URLField(max_length=1000)),
            ],
            options={
                'unique_together': {('product', 'vender', 'color')},
            },
        ),
    ]
