# Generated by Django 2.2.6 on 2019-11-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191105_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
