# Generated by Django 2.2.6 on 2019-11-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20191105_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_image',
            new_name='product_images',
        ),
    ]
