# Generated by Django 2.2.6 on 2019-11-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20191105_1342'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='inventory',
        #     old_name='vender',
        #     new_name='vendor',
        # ),
        migrations.AddField(
            model_name='inventory',
            name='product_image',
            field=models.URLField(default='http://'),
            preserve_default=False,
        ),
        # migrations.AlterUniqueTogether(
        #     name='inventory',
        #     unique_together={('product', 'vendor', 'color')},
        # ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_images',
        ),
    ]
